nohup: ignoring input
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
192.168.0.163 - - [06/Jan/2025 10:04:24] "GET / HTTP/1.1" 200 -
192.168.0.163 - - [06/Jan/2025 10:04:24] "GET /favicon.ico HTTP/1.1" 404 -
[2025-01-06 10:04:24,677] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:04:24] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:04:37] "GET / HTTP/1.1" 200 -
[2025-01-06 10:04:38,809] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:04:38] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:04:41] "GET / HTTP/1.1" 200 -
[2025-01-06 10:04:42,211] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:04:42] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:06:09] "GET / HTTP/1.1" 200 -
[2025-01-06 10:06:14,604] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:06:14] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:06:46] "GET / HTTP/1.1" 200 -
[2025-01-06 10:07:01,077] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:07:01] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:07:56] "GET / HTTP/1.1" 200 -
[2025-01-06 10:07:57,764] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:07:57] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:08:46] "GET / HTTP/1.1" 200 -
[2025-01-06 10:08:57,670] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:08:57] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
192.168.0.163 - - [06/Jan/2025 10:09:04] "POST /send_command HTTP/1.1" 200 -
[2025-01-06 10:09:08,882] ERROR in app: Exception on /get_logs [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 102, in get_logs
    logs_data = get_test_logs(page, per_page)
  File "app.py", line 51, in get_test_logs
    logs = list(reader)[1:]  # Skip header row
_csv.Error: line contains NULL byte
192.168.0.163 - - [06/Jan/2025 10:09:08] "GET /get_logs?page=1&per_page=10 HTTP/1.1" 500 -
